import { Archivo, Roboto_Flex } from "next/font/google";
import { Footer, Navbar } from "@/components/sections";
import { cn } from "@/libs/utils";
import "@/styles/globals.css";
import { Layout } from "@/components/ui";
import { Suspense } from "react";

export const metadata = {
	title: "Japp Media | Tu proximo servicio web",
	description: "Generated by Next.js",
};

export const font_heading = Archivo({
	weight: ["300", "400", "600", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-heading",
});

export const font_body = Roboto_Flex({
	weight: ["200", "300", "400", "600", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-body",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={cn(
					font_heading.variable,
					font_body.variable,
					`bg-background text-white flex flex-col min-h-[100vh]`
				)}
			>
				<Suspense fallback={<div>Loading...</div>}>
					<Navbar /> 
				</Suspense>
				<Layout>{children}</Layout>
				<Footer />
			</body>
		</html>
	);
}
