import { Footer, Navbar } from '@/components/sections'
import '@/styles/globals.css'

export const metadata = {
  title: 'Japp Media | Tu proximo servicio web',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-background text-white'>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
